# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: "Bahay", password: "test", is_admin: "true", email: "b@gmail.com", image: "https://www.aos.org/AOS/media/Content-Images/Orchids/orchid-care-phal.jpg")
User.create(username: "Pinar", password: "test", is_admin: "false", email: "p@gmail.com", image: "https://cdn.shopify.com/s/files/1/0997/4496/files/happy_cat_grande.jpg?v=1546467847")

Charity.create(user_id: 1, name: "Cocoon House", image: "https://www.beheard.live/wp-content/uploads/2019/03/cocoonhouse2.png", address: "3530 Colby Avenue, Everett, WA 98201", city: "Everett", description: "More than 34% of the total homeless population is under the age of 24. Cocoon House is a non-profit that conducts outreach to, and provides short and long term housing for homeless and at-risk young people, including their children. Parents of teens can also find support for themselves and their families at Cocoon House so that young people do not become homeless.")
Charity.create(user_id: 1, name: "Reach Out", image: "https://www.homelessshelterdirectory.org/gallery/17062__xex.jpg", address: "1229 W Smith St Kent, WA 98032", city: "Kent", description: "Reach Out Homeless Winter Shelter Programs provide shelter, daily meals and case management services to homeless adults in South King County. The program is operated during the winter months and relies on partnerships with area congregations, community organizations, businesses, and public and private contributors, as well as many caring individuals and families.The program’s goal is to serve those in need by providing support to assist them in achieving self-sufficiency, in turn strengthening our community.")
Charity.create(user_id: 1, name: "Metropolitan Development Council", image: "https://www.degreesofchange.org/wp-content/uploads/2014/06/logo-mdc-on-white-300x200.png", address: "945 Fawcett Ave, Tacoma, WA 98402", city: "Tacoma", description: "MDC – Metropolitan Development Council is a vital community resource for Tacoma and Pierce County. Founded in 1964 as a non-profit Community Action Agency, MDC responds to community needs by providing services in the areas of healthcare, housing, education, and employment that address the challenges faced by low-income individuals and families.")
Charity.create(user_id: 1, name: "Hope Creek", image: "https://hopecreekcf.org/wp-content/uploads/2014/02/hopecreek_logo.png", address: "4326 148th St SE, Mill Creek, WA 98012", city: "Mill Creek", description: "Hope Creek Charitable Foundation is a 501c3 non-profit organization located in Mill Creek, WA that serves those in need in our community. We believe in serving our community with grace and compassion, building relationships along the way.")
Charity.create(user_id: 1, name: "Hopelink", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTTvJ2NB19Q39fDk8VK7oWs-VI8rXH29co-eo4AnUg5i6IrOAX7", address: "14812 Main St. Bellevue, WA 98007", city: "Bellevue", description: "Since 1971, Hopelink has served homeless and low-income families, children, seniors and people with disabilities in King and Snohomish counties; providing stability and helping people gain the skills and knowledge they need to exit poverty for good.")
Charity.create(user_id: 1, name: "Washington Women In Need", image: "https://volunteer.uwkc.org/content/volunteer.uwkc.org/agency/69209.jpg?1531766878", address: "232 5th Ave S, Suite 201, Kirkland, WA 98033", city: "Kirkland", description: "WWIN believes in the power of determined women to transform their lives and the course of their families’ lives for generations to come. We address a deep need in society, providing women a hand up to improve their futures. This in turn strengthens their families and our society as a whole.")
Charity.create(user_id: 1, name: "Seattle Works", image: "https://pbs.twimg.com/profile_images/920768117340479488/87pgHq2-_400x400.jpg", address: "240 2nd Ave S #208, Seattle, WA 98104", city: "Seattle", description: "Seattle Works is striving to build a diverse and welcoming community through focusing on equity in all aspects of our work.Seattle Works' core values are: We are building a diverse, welcoming community. We make decisions that are objective and mindful. We believe that every contribution counts. We have fun.")
Charity.create(user_id: 1, name: "Compass Housing Alliance", image: "https://www.compasshousingalliance.org/wp-content/uploads/2019/12/CHA-logo2-square-large.png", address: "77 S Washington St, Seattle, WA 98104", city: "Seattle", description: "We are a leading provider and developer of essential services and affordable housing for men, women, veterans, and families who are low-income or experiencing homelessness in the Puget Sound region. Our portfolio includes day services, emergency shelter, transitional housing, and affordable housing at 23 locations. Through partnerships with local congregations, governments and service providers, we offer creative programming that meets the needs of a changing community. We hope you’ll join us in this important work. Because safe, caring communities begin with caring people.")
Charity.create(user_id: 1, name: "Jubilee Women's Center", image: "https://volunteer.uwkc.org/content/volunteer.uwkc.org/agency/61357.jpg?1564763293", address: "620 18th Ave E, Seattle, WA 98112", city: "Seattle", description: "Jubilee’s residential program provides affordable community housing, holistic support services, on-site case managers, learning opportunities, and a focus on employment preparation to advance each woman on her path out of poverty. Jubilee also provides low-income women in the community with free referrals, computer access, and clothing.")
Charity.create(user_id: 1, name: "REACH", image: "https://volunteer.uwkc.org/content/volunteer.uwkc.org/agency/77618.jpg?1505149078?area=agency", address: "3604 NE 10th Ct, Renton, WA 98056", city: "Renton", description: "The REACH Center of Hope is a day and night shelter for women, children, and families. The Center of Hope partners with a number of agencies to ensure that our clients are accessing every avenue possible as they make their journey from homelessness to stability. The Day Center is open Monday through Friday, from 7:30AM to 4:00PM, with the Night Shelter operating 365 nights a year.")
 
Request.create(user_id: 2, charity_id: 1, expiration_date: "07/01/2020", info: "Salmon, 5 lbs", status: "closed", category: "Food")
Request.create(user_id: 2, charity_id: 1, expiration_date: "07/11/2020", info: "Apples, 10 lbs", status: "pending", category: "Food")
Request.create(user_id: 1, charity_id: 1, expiration_date: "07/25/2020", info: "Canned Kidney Beans, 10 Servings", status: "open", category: "Food")
Request.create(user_id: 2, charity_id: 8, expiration_date: "08/05/2020", info: "Diapers for all ages", status: "closed", category: "Hygiene Product")
Request.create(user_id: 2, charity_id: 4, expiration_date: "08/28/2020", info: "Toothbrushes for 20 people", status: "approved", category: "Hygiene Product")
Request.create(user_id: 2, charity_id: 9, expiration_date: "09/04/2020", info: "Volunteer to serve food on 09/04/2020, 4:00 - 5:00 pm", status: "pending", category: "Volunteer")
Request.create(user_id: 1, charity_id: 3, expiration_date: "09/10/2020", info: "Socks for all ages", status: "open", category: "Clothing")
Request.create(user_id: 1, charity_id: 6, expiration_date: "10/01/2020", info: "Volunteer to pack bulk food on 10/01/2020, 9:30 - 11:00 am", status: "open", category: "Volunteer")
Request.create(user_id: 1, charity_id: 3, expiration_date: "10/11/2020", info: "Blankets for 20 people", status: "open", category: "Clothing")